## This is the configuration file for Netlify
## https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  command = "npm run generate" # how to build your project
  functions = "netlify/functions" # where Netlify Functions live
  publish = "dist" # where the built project lives

## Learn more about redirects here
## https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
## https://docs.netlify.com/routing/redirects/redirect-options/

[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false
  [plugins.inputs.postBuild]
    enable = true
